# Generated by Django 2.1.15 on 2020-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='derived_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
