# Generated by Django 2.2.16 on 2020-10-22 11:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_website_derived_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
