# Generated by Django 2.2.16 on 2020-11-21 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201106_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
