# Generated by Django 2.2.16 on 2020-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201207_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedwebsite',
            name='journal',
            field=models.TextField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curatedwebsite',
            name='year',
            field=models.SmallIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
