# Generated by Django 2.2.16 on 2020-12-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201207_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedwebsite',
            name='tags',
            field=models.ManyToManyField(related_name='curated', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='curatedwebsite',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curated', to='main.Website'),
        ),
    ]
