# Generated by Django 2.2.16 on 2020-12-08 00:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201207_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedwebsite',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
    ]
