# Generated by Django 2.2.16 on 2020-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_curatedwebsite_contact_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedwebsite',
            name='days_reminder',
            field=models.IntegerField(default=0),
        ),
    ]
