# Generated by Django 2.2.16 on 2021-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_curatedwebsite_days_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
