# Generated by Django 3.2 on 2021-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210422_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_size', models.BigIntegerField()),
                ('num_calls', models.BigIntegerField()),
            ],
        ),
    ]
