# Generated by Django 3.2 on 2021-04-23 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_globalstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstatistics',
            name='weekdays_offline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='globalstatistics',
            name='weekdays_online',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
