# Generated by Django 3.2 on 2021-04-23 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210423_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstatistics',
            name='recovery_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
