# Generated by Django 2.2.16 on 2021-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_globalstatistics_recovery_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='biotools_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
