# Generated by Django 2.2.16 on 2021-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210424_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='biotools_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
