# Generated by Django 2.2.16 on 2021-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210424_1748'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='websitecall',
            index=models.Index(fields=['datetime'], name='main_websit_datetim_ab3af9_idx'),
        ),
        migrations.AddIndex(
            model_name='websitecall',
            index=models.Index(fields=['-datetime'], name='main_websit_datetim_b32955_idx'),
        ),
    ]
