# Generated by Django 2.2.16 on 2021-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210721_2000'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='websitecall',
            name='main_websit_datetim_ab3af9_idx',
        ),
        migrations.RemoveIndex(
            model_name='websitecall',
            name='main_websit_datetim_b32955_idx',
        ),
        migrations.AddIndex(
            model_name='websitecall',
            index=models.Index(fields=['datetime', 'website'], name='main_websit_datetim_3801d7_idx'),
        ),
    ]
