dependencies:
  - python=3.8.5
  - wheel=0.35.1
  - psycopg2=2.8.5  # https://github.com/psycopg/psycopg2

  - pip:
    - django==2.2.16
    - django-environ==0.4.5
    - redis==3.5.3
    - django-redis==4.12.1  # https://github.com/niwinz/django-redis
    - celery==4.4.7  # pyup: <5.0  # https://github.com/celery/celery
    - flower==0.9.5  # https://github.com/mher/flower
    - tornado<6.0.0  # needed for flower because they don't fix it to a version in their 0.9.2 version
# Your custom requirements go here
    - tqdm==4.50.2
