dependencies:
  - python=3.8.5
  - wheel=0.35.1
  - psycopg2=2.8.5  # https://github.com/psycopg/psycopg2
  - conda-forge::pyahocorasick=1.4.0 # doesn't build over pip

  - pip:
    - django==2.2.16
    - django-environ==0.4.5
    - redis==3.5.3
    - django-redis==4.12.1  # https://github.com/niwinz/django-redis
    - celery==4.4.7  # pyup: <5.0  # https://github.com/celery/celery
    - flower==0.9.5  # https://github.com/mher/flower
    - tqdm==4.50.2
    - orjson==3.4.1
    - pandas==1.1.3
    - django-cache-memoize
    - django-datatables-view==1.19.1
    - django-choices==1.7.1
    - testfixtures
    - django-recaptcha==2.0.6
    - django_compressor==2.4.1
