dependencies:
  - pip:
    - Werkzeug==1.0.1
    - ipdb==0.13.4
    - prompt-toolkit==3.0.8
    - django-debug-toolbar-request-history==0.1.3  # allows to track ajax requests
    - django-debug-toolbar==3.1.1
    - django-extensions==3.0.9
