dependencies:
  - Werkzeug=0.14.1  # https://github.com/pallets/werkzeug
  - conda-forge::ipdb=0.11  # https://github.com/gotcha/ipdb
  - conda-forge::prompt_toolkit=2.0.10 # Required to fix implicit dependency updates in ipdb: https://github.com/ipython/ipython/issues/11962
  - Sphinx=1.7.5  # https://github.com/sphinx-doc/sphinx

# Django
# ------------------------------------------------------------------------------
  - conda-forge::django-debug-toolbar=1.9.1  # https://github.com/jazzband/django-debug-toolbar
  - conda-forge::django-extensions=2.0.7  # https://github.com/django-extensions/django-extensions

  - pip:
    - django-debug-toolbar-request-history==0.0.7  # allows to track ajax requests
